# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-08-02 14:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_aur', '0003_package_is_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='arch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='django_aur.Arch'),
        ),
        migrations.AlterField(
            model_name='update',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='django_aur.Package'),
        ),
    ]
